LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
 
LOCAL_MODULE		:= libogre
LOCAL_C_INCLUDES	:= $(LOCAL_PATH)/ogre $(LOCAL_PATH)/ogre/OgreMain/include $(LOCAL_PATH)/ogre/dependencies $(LOCAL_PATH)/ogre/dependencies/freeimage $(LOCAL_PATH)/ogre/Components/RTShaderSystem/include $(LOCAL_PATH)/ogre/RenderSystems/GLES2/include $(LOCAL_PATH)/ogre/RenderSystems/GLES2/include $(LOCAL_PATH)/ogre/RenderSystems/GLES2/src/GLSLES/include $(LOCAL_PATH)/ogre/RenderSystems/GLES2/include/Android $(LOCAL_PATH)/ogre/PlugIns/ParticleFX/include $(LOCAL_PATH)/../../Dependencies/jni/freetype/include $(LOCAL_PATH)/../../Dependencies/jni/freeimage $(LOCAL_PATH)/../../Dependencies/jni
LOCAL_CFLAGS		:= -DFREEIMAGE_LIB=1 -DOGRE_NONCLIENT_BUILD=1
LOCAL_LDLIBS		:= -L$(LOCAL_PATH)/../lib -lfreeimage -lzzip -ldl -llog -lz -lGLESv2 -lfreetype
LOCAL_SRC_FILES		:= ogre/OgreMain/src/OgreAlignedAllocator.cpp\
	ogre/OgreMain/src/OgreAnimable.cpp\
	ogre/OgreMain/src/OgreAnimation.cpp\
	ogre/OgreMain/src/OgreAnimationState.cpp\
	ogre/OgreMain/src/OgreAnimationTrack.cpp\
	ogre/OgreMain/src/OgreArchiveManager.cpp\
	ogre/OgreMain/src/OgreAutoParamDataSource.cpp\
	ogre/OgreMain/src/OgreAxisAlignedBox.cpp\
	ogre/OgreMain/src/OgreBillboard.cpp\
	ogre/OgreMain/src/OgreBillboardChain.cpp\
	ogre/OgreMain/src/OgreBillboardParticleRenderer.cpp\
	ogre/OgreMain/src/OgreBillboardSet.cpp\
	ogre/OgreMain/src/OgreBone.cpp\
	ogre/OgreMain/src/OgreBorderPanelOverlayElement.cpp\
	ogre/OgreMain/src/OgreCamera.cpp\
	ogre/OgreMain/src/OgreCodec.cpp\
	ogre/OgreMain/src/OgreColourValue.cpp\
	ogre/OgreMain/src/OgreCommon.cpp\
	ogre/OgreMain/src/OgreCompositionPass.cpp\
	ogre/OgreMain/src/OgreCompositionTargetPass.cpp\
	ogre/OgreMain/src/OgreCompositionTechnique.cpp\
	ogre/OgreMain/src/OgreCompositor.cpp\
	ogre/OgreMain/src/OgreCompositorChain.cpp\
	ogre/OgreMain/src/OgreCompositorInstance.cpp\
	ogre/OgreMain/src/OgreCompositorManager.cpp\
	ogre/OgreMain/src/OgreConfigFile.cpp\
	ogre/OgreMain/src/OgreControllerManager.cpp\
	ogre/OgreMain/src/OgreConvexBody.cpp\
	ogre/OgreMain/src/OgreDataStream.cpp\
	ogre/OgreMain/src/OgreDDSCodec.cpp\
	ogre/OgreMain/src/OgreDefaultHardwareBufferManager.cpp\
	ogre/OgreMain/src/OgreDefaultSceneQueries.cpp\
	ogre/OgreMain/src/OgreDeflate.cpp\
	ogre/OgreMain/src/OgreDepthBuffer.cpp\
	ogre/OgreMain/src/OgreDistanceLodStrategy.cpp\
	ogre/OgreMain/src/OgreDualQuaternion.cpp\
	ogre/OgreMain/src/OgreDynLib.cpp\
	ogre/OgreMain/src/OgreDynLibManager.cpp\
	ogre/OgreMain/src/OgreEdgeListBuilder.cpp\
	ogre/OgreMain/src/OgreEntity.cpp\
	ogre/OgreMain/src/OgreException.cpp\
	ogre/OgreMain/src/OgreExternalTextureSource.cpp\
	ogre/OgreMain/src/OgreExternalTextureSourceManager.cpp\
	ogre/OgreMain/src/OgreFileSystem.cpp\
	ogre/OgreMain/src/OgreFont.cpp\
	ogre/OgreMain/src/OgreFontManager.cpp\
	ogre/OgreMain/src/OgreFreeImageCodec.cpp\
	ogre/OgreMain/src/OgreFrustum.cpp\
	ogre/OgreMain/src/OgreGpuProgram.cpp\
	ogre/OgreMain/src/OgreGpuProgramManager.cpp\
	ogre/OgreMain/src/OgreGpuProgramParams.cpp\
	ogre/OgreMain/src/OgreGpuProgramUsage.cpp\
	ogre/OgreMain/src/OgreHardwareBufferManager.cpp\
	ogre/OgreMain/src/OgreHardwareIndexBuffer.cpp\
	ogre/OgreMain/src/OgreHardwareOcclusionQuery.cpp\
	ogre/OgreMain/src/OgreHardwarePixelBuffer.cpp\
	ogre/OgreMain/src/OgreHardwareVertexBuffer.cpp\
	ogre/OgreMain/src/OgreHighLevelGpuProgram.cpp\
	ogre/OgreMain/src/OgreHighLevelGpuProgramManager.cpp\
	ogre/OgreMain/src/OgreImage.cpp\
	ogre/OgreMain/src/OgreInstanceBatch.cpp\
	ogre/OgreMain/src/OgreInstanceBatchHW.cpp\
	ogre/OgreMain/src/OgreInstanceBatchHW_VTF.cpp\
	ogre/OgreMain/src/OgreInstanceBatchShader.cpp\
	ogre/OgreMain/src/OgreInstanceBatchVTF.cpp\
	ogre/OgreMain/src/OgreInstancedEntity.cpp\
	ogre/OgreMain/src/OgreInstancedGeometry.cpp\
	ogre/OgreMain/src/OgreInstanceManager.cpp\
	ogre/OgreMain/src/OgreKeyFrame.cpp\
	ogre/OgreMain/src/OgreLight.cpp\
	ogre/OgreMain/src/OgreLodStrategy.cpp\
	ogre/OgreMain/src/OgreLodStrategyManager.cpp\
	ogre/OgreMain/src/OgreLog.cpp\
	ogre/OgreMain/src/OgreLogManager.cpp\
	ogre/OgreMain/src/OgreManualObject.cpp\
	ogre/OgreMain/src/OgreMaterial.cpp\
	ogre/OgreMain/src/OgreMaterialManager.cpp\
	ogre/OgreMain/src/OgreMaterialSerializer.cpp\
	ogre/OgreMain/src/OgreMath.cpp\
	ogre/OgreMain/src/OgreMatrix3.cpp\
	ogre/OgreMain/src/OgreMatrix4.cpp\
	ogre/OgreMain/src/OgreMemoryAllocatedObject.cpp\
	ogre/OgreMain/src/OgreMemoryNedAlloc.cpp\
	ogre/OgreMain/src/OgreMemoryNedPooling.cpp\
	ogre/OgreMain/src/OgreMemoryTracker.cpp\
	ogre/OgreMain/src/OgreMesh.cpp\
	ogre/OgreMain/src/OgreMeshManager.cpp\
	ogre/OgreMain/src/OgreMeshSerializer.cpp\
	ogre/OgreMain/src/OgreMeshSerializerImpl.cpp\
	ogre/OgreMain/src/OgreMovableObject.cpp\
	ogre/OgreMain/src/OgreMovablePlane.cpp\
	ogre/OgreMain/src/OgreNode.cpp\
	ogre/OgreMain/src/OgreNumerics.cpp\
	ogre/OgreMain/src/OgreOptimisedUtil.cpp\
	ogre/OgreMain/src/OgreOptimisedUtilGeneral.cpp\
	ogre/OgreMain/src/OgreOptimisedUtilSSE.cpp\
	ogre/OgreMain/src/OgreOverlay.cpp\
	ogre/OgreMain/src/OgreOverlayContainer.cpp\
	ogre/OgreMain/src/OgreOverlayElement.cpp\
	ogre/OgreMain/src/OgreOverlayElementCommands.cpp\
	ogre/OgreMain/src/OgreOverlayElementFactory.cpp\
	ogre/OgreMain/src/OgreOverlayManager.cpp\
	ogre/OgreMain/src/OgrePanelOverlayElement.cpp\
	ogre/OgreMain/src/OgreParticle.cpp\
	ogre/OgreMain/src/OgreParticleEmitter.cpp\
	ogre/OgreMain/src/OgreParticleEmitterCommands.cpp\
	ogre/OgreMain/src/OgreParticleIterator.cpp\
	ogre/OgreMain/src/OgreParticleSystem.cpp\
	ogre/OgreMain/src/OgreParticleSystemManager.cpp\
	ogre/OgreMain/src/OgrePass.cpp\
	ogre/OgreMain/src/OgrePatchMesh.cpp\
	ogre/OgreMain/src/OgrePatchSurface.cpp\
	ogre/OgreMain/src/OgrePixelCountLodStrategy.cpp\
	ogre/OgreMain/src/OgrePixelFormat.cpp\
	ogre/OgreMain/src/OgrePlane.cpp\
	ogre/OgreMain/src/OgrePlatformInformation.cpp\
	ogre/OgreMain/src/OgrePolygon.cpp\
	ogre/OgreMain/src/OgrePose.cpp\
	ogre/OgreMain/src/OgrePrecompiledHeaders.cpp\
	ogre/OgreMain/src/OgrePredefinedControllers.cpp\
	ogre/OgreMain/src/OgrePrefabFactory.cpp\
	ogre/OgreMain/src/OgreProfiler.cpp\
	ogre/OgreMain/src/OgreProgressiveMesh.cpp\
	ogre/OgreMain/src/OgrePVRTCCodec.cpp\
	ogre/OgreMain/src/OgreQuaternion.cpp\
	ogre/OgreMain/src/OgreRectangle2D.cpp\
	ogre/OgreMain/src/OgreRenderQueue.cpp\
	ogre/OgreMain/src/OgreRenderQueueInvocation.cpp\
	ogre/OgreMain/src/OgreRenderQueueSortingGrouping.cpp\
	ogre/OgreMain/src/OgreRenderSystem.cpp\
	ogre/OgreMain/src/OgreRenderSystemCapabilities.cpp\
	ogre/OgreMain/src/OgreRenderSystemCapabilitiesManager.cpp\
	ogre/OgreMain/src/OgreRenderSystemCapabilitiesSerializer.cpp\
	ogre/OgreMain/src/OgreRenderTarget.cpp\
	ogre/OgreMain/src/OgreRenderTexture.cpp\
	ogre/OgreMain/src/OgreRenderToVertexBuffer.cpp\
	ogre/OgreMain/src/OgreRenderWindow.cpp\
	ogre/OgreMain/src/OgreResource.cpp\
	ogre/OgreMain/src/OgreResourceBackgroundQueue.cpp\
	ogre/OgreMain/src/OgreResourceGroupManager.cpp\
	ogre/OgreMain/src/OgreResourceManager.cpp\
	ogre/OgreMain/src/OgreRibbonTrail.cpp\
	ogre/OgreMain/src/OgreRoot.cpp\
	ogre/OgreMain/src/OgreRotationSpline.cpp\
	ogre/OgreMain/src/OgreSceneManager.cpp\
	ogre/OgreMain/src/OgreSceneManagerEnumerator.cpp\
	ogre/OgreMain/src/OgreSceneNode.cpp\
	ogre/OgreMain/src/OgreSceneQuery.cpp\
	ogre/OgreMain/src/OgreScriptCompiler.cpp\
	ogre/OgreMain/src/OgreScriptLexer.cpp\
	ogre/OgreMain/src/OgreScriptParser.cpp\
	ogre/OgreMain/src/OgreScriptTranslator.cpp\
	ogre/OgreMain/src/OgreSearchOps.cpp\
	ogre/OgreMain/src/OgreSerializer.cpp\
	ogre/OgreMain/src/OgreShadowCameraSetup.cpp\
	ogre/OgreMain/src/OgreShadowCameraSetupFocused.cpp\
	ogre/OgreMain/src/OgreShadowCameraSetupLiSPSM.cpp\
	ogre/OgreMain/src/OgreShadowCameraSetupPlaneOptimal.cpp\
	ogre/OgreMain/src/OgreShadowCameraSetupPSSM.cpp\
	ogre/OgreMain/src/OgreShadowCaster.cpp\
	ogre/OgreMain/src/OgreShadowTextureManager.cpp\
	ogre/OgreMain/src/OgreShadowVolumeExtrudeProgram.cpp\
	ogre/OgreMain/src/OgreSimpleRenderable.cpp\
	ogre/OgreMain/src/OgreSimpleSpline.cpp\
	ogre/OgreMain/src/OgreSkeleton.cpp\
	ogre/OgreMain/src/OgreSkeletonInstance.cpp\
	ogre/OgreMain/src/OgreSkeletonManager.cpp\
	ogre/OgreMain/src/OgreSkeletonSerializer.cpp\
	ogre/OgreMain/src/OgreSmallVector.cpp\
	ogre/OgreMain/src/OgreStaticGeometry.cpp\
	ogre/OgreMain/src/OgreStreamSerialiser.cpp\
	ogre/OgreMain/src/OgreString.cpp\
	ogre/OgreMain/src/OgreStringConverter.cpp\
	ogre/OgreMain/src/OgreStringInterface.cpp\
	ogre/OgreMain/src/OgreSubEntity.cpp\
	ogre/OgreMain/src/OgreSubMesh.cpp\
	ogre/OgreMain/src/OgreTagPoint.cpp\
	ogre/OgreMain/src/OgreTangentSpaceCalc.cpp\
	ogre/OgreMain/src/OgreTechnique.cpp\
	ogre/OgreMain/src/OgreTextAreaOverlayElement.cpp\
	ogre/OgreMain/src/OgreTexture.cpp\
	ogre/OgreMain/src/OgreTextureManager.cpp\
	ogre/OgreMain/src/OgreTextureUnitState.cpp\
	ogre/OgreMain/src/OgreUnifiedHighLevelGpuProgram.cpp\
	ogre/OgreMain/src/OgreUserObjectBindings.cpp\
	ogre/OgreMain/src/OgreUTFString.cpp\
	ogre/OgreMain/src/OgreVector2.cpp\
	ogre/OgreMain/src/OgreVector3.cpp\
	ogre/OgreMain/src/OgreVector4.cpp\
	ogre/OgreMain/src/OgreVertexIndexData.cpp\
	ogre/OgreMain/src/OgreViewport.cpp\
	ogre/OgreMain/src/OgreWindowEventUtilities.cpp\
	ogre/OgreMain/src/OgreWireBoundingBox.cpp\
	ogre/OgreMain/src/OgreWorkQueue.cpp\
	ogre/OgreMain/src/OgreZip.cpp\
	ogre/OgreMain/src/OgreStringSerialiser.cpp\
	ogre/OgreMain/src/Android/OgreTimer.cpp\
	ogre/OgreMain/src/Android/OgreConfigDialog.cpp\
	ogre/OgreMain/src/Android/OgreErrorDialog.cpp\
	ogre/OgreMain/src/Threading/OgreDefaultWorkQueueStandard.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderExIntegratedPSSM3.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderExLayeredBlending.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderExNormalMapLighting.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderExPerPixelLighting.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderExHardwareSkinning.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderFFPColour.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderFFPFog.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderFFPLighting.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderFFPRenderStateBuilder.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderFFPTexturing.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderFFPTransform.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderFunction.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderFunctionAtom.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderGenerator.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderGLSLESProgramProcessor.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderGLSLESProgramWriter.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderMaterialSerializerListener.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderParameter.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderProgram.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderProgramManager.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderProgramProcessor.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderProgramSet.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderProgramWriter.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderProgramWriterManager.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderRenderState.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderScriptTranslator.cpp\
	ogre/Components/RTShaderSystem/src/OgreShaderSubRenderState.cpp\
	ogre/RenderSystems/GLES2/src/OgreGLES2Context.cpp\
	ogre/RenderSystems/GLES2/src/OgreGLES2DefaultHardwareBufferManager.cpp\
	ogre/RenderSystems/GLES2/src/OgreGLES2DepthBuffer.cpp\
	ogre/RenderSystems/GLES2/src/OgreGLES2EngineDll.cpp\
	ogre/RenderSystems/GLES2/src/OgreGLES2FBOMultiRenderTarget.cpp\
	ogre/RenderSystems/GLES2/src/OgreGLES2FBORenderTexture.cpp\
	ogre/RenderSystems/GLES2/src/OgreGLES2FrameBufferObject.cpp\
	ogre/RenderSystems/GLES2/src/OgreGLES2GpuProgram.cpp\
	ogre/RenderSystems/GLES2/src/OgreGLES2GpuProgramManager.cpp\
	ogre/RenderSystems/GLES2/src/OgreGLES2HardwareBufferManager.cpp\
	ogre/RenderSystems/GLES2/src/OgreGLES2HardwareIndexBuffer.cpp\
	ogre/RenderSystems/GLES2/src/OgreGLES2HardwareOcclusionQuery.cpp\
	ogre/RenderSystems/GLES2/src/OgreGLES2HardwarePixelBuffer.cpp\
	ogre/RenderSystems/GLES2/src/OgreGLES2HardwareVertexBuffer.cpp\
	ogre/RenderSystems/GLES2/src/OgreGLES2PixelFormat.cpp\
	ogre/RenderSystems/GLES2/src/OgreGLES2Plugin.cpp\
	ogre/RenderSystems/GLES2/src/OgreGLES2RenderSystem.cpp\
	ogre/RenderSystems/GLES2/src/OgreGLES2RenderTexture.cpp\
	ogre/RenderSystems/GLES2/src/OgreGLES2Support.cpp\
	ogre/RenderSystems/GLES2/src/OgreGLES2Texture.cpp\
	ogre/RenderSystems/GLES2/src/OgreGLES2TextureManager.cpp\
	ogre/RenderSystems/GLES2/src/GLSLES/src/OgreGLSLESExtSupport.cpp\
	ogre/RenderSystems/GLES2/src/GLSLES/src/OgreGLSLESGpuProgram.cpp\
	ogre/RenderSystems/GLES2/src/GLSLES/src/OgreGLSLESLinkProgram.cpp\
	ogre/RenderSystems/GLES2/src/GLSLES/src/OgreGLSLESLinkProgramManager.cpp\
	ogre/RenderSystems/GLES2/src/GLSLES/src/OgreGLSLESProgramCommon.cpp\
	ogre/RenderSystems/GLES2/src/GLSLES/src/OgreGLSLESPreprocessor.cpp\
	ogre/RenderSystems/GLES2/src/GLSLES/src/OgreGLSLESProgram.cpp\
	ogre/RenderSystems/GLES2/src/GLSLES/src/OgreGLSLESProgramFactory.cpp\
	ogre/RenderSystems/GLES2/src/GLSLES/src/OgreGLSLESProgramManagerCommon.cpp\
	ogre/RenderSystems/GLES2/src/GLSLES/src/OgreGLSLESProgramPipeline.cpp\
	ogre/RenderSystems/GLES2/src/GLSLES/src/OgreGLSLESProgramPipelineManager.cpp\
	ogre/RenderSystems/GLES2/src/Android/OgreAndroidGLContext.cpp\
	ogre/RenderSystems/GLES2/src/Android/OgreAndroidGLSupport.cpp\
	ogre/RenderSystems/GLES2/src/Android/OgreAndroidWindow.cpp\
	ogre/PlugIns/ParticleFX/src/OgreAreaEmitter.cpp\
	ogre/PlugIns/ParticleFX/src/OgreBoxEmitter.cpp\
	ogre/PlugIns/ParticleFX/src/OgreColourFaderAffector.cpp\
	ogre/PlugIns/ParticleFX/src/OgreColourFaderAffector2.cpp\
	ogre/PlugIns/ParticleFX/src/OgreColourImageAffector.cpp\
	ogre/PlugIns/ParticleFX/src/OgreColourInterpolatorAffector.cpp\
	ogre/PlugIns/ParticleFX/src/OgreCylinderEmitter.cpp\
	ogre/PlugIns/ParticleFX/src/OgreDeflectorPlaneAffector.cpp\
	ogre/PlugIns/ParticleFX/src/OgreDirectionRandomiserAffector.cpp\
	ogre/PlugIns/ParticleFX/src/OgreEllipsoidEmitter.cpp\
	ogre/PlugIns/ParticleFX/src/OgreHollowEllipsoidEmitter.cpp\
	ogre/PlugIns/ParticleFX/src/OgreLinearForceAffector.cpp\
	ogre/PlugIns/ParticleFX/src/OgreParticleFXPlugin.cpp\
	ogre/PlugIns/ParticleFX/src/OgrePointEmitter.cpp\
	ogre/PlugIns/ParticleFX/src/OgreRingEmitter.cpp\
	ogre/PlugIns/ParticleFX/src/OgreRotationAffector.cpp\
	ogre/PlugIns/ParticleFX/src/OgreScaleAffector.cpp
 
LOCAL_STATIC_LIBRARIES := libfreeimage libft2 libzzip
 
include $(BUILD_SHARED_LIBRARY)
